### PR TITLE
Fixing Peerbook gates

### LINKED ISSUE #337: Fix peerbook hosts display on map
For gates we got from peerbook the expand icon should be replaced with
the address book icon. Clickng the icom willopen https://peerbook.io in
the apps browser.

### LINKED ISSUE #349: Notify when connecting to unverified gate
**Describe the bug**
If a gate that was added from peerbook is unverified, then I'm unable to click its map element but I can type in `connect [gate]` and I get an hourglass that will always fail. We should check inside `connect` if the gate is unverified (or offline) and notify the user.

**To Reproduce**
1. Add a host to your peerbook but don't verify it
2. Reload T7
3. Type in TWR `connect` with the respective name

**Additional Context**
I wonder if we should allow users to click an unverified gate and show them an error message instead (as clicking without anything happening is weird and the user needs to know what is the problem).

### PR DESCRIPTION
**Pull request by eyal-sasson**
Closes #337, closes #349.

### CODE REVIEW

File: src/commands.ts [hunk 1]
```diff
@@ -162,6 +162,12 @@ async function connectCMD(shell:Shell, args: string[]) {
     const gate: Gate = shell.getGate(hostname)
     if (!gate)
         return shell.t.writeln(`Host not found: ${hostname}`)
+    if (gate.fp) {
+        if (!gate.verified)
+            return shell.t.writeln("Host unverified, please verify at https://peerbook.io")
```
Comment (daonb) [inline src/commands.ts:167]: Better to get the server url from the conf.

File: src/terminal7.js [hunk 2]
```diff
@@ -864,8 +864,11 @@ export class Terminal7 {
                 if (deltaT < this.conf.ui.quickest_press) {
                     // that's for the refresh and static host add
                     if (isExpand) {
-                        this.map.shell.runCommand("edit", [gate.name])
-                    } else if (!gate.fp || gate.verified && gate.online) {
+                        if (gate.fp)
+                            window.open("https://peerbook.io", "_blank")
```
Comment (daonb) [inline src/terminal7.js:868]: here too, get the url from conf

File: src/map.ts [hunk 3]
```diff
@@ -105,10 +105,13 @@ export class T7Map {
         this.refresh()
     }
 
-    update({ e, name, boarding, offline, unverified }): void {
+    update({ e, name, boarding, offline, unverified, peerbook }): void {
 
         const b = e.children[0]
-        b.innerHTML = `<i class="f7-icons expand-gate">expand</i>${name}`
+        if (peerbook)
+            b.innerHTML = `<i class="f7-icons expand-gate">person_2_square_stack</i>${name}`
```
Comment (daonb) [inline src/map.ts:112]: The icon is bit busy. Try using `book`

**Review by daonb — CHANGES_REQUESTED** [review]
Nice!
